### ISSUE TITLE
Mint, burn, setTotalSupply, setPaused, etc should not add to token.ts as standard rather added them to extensions

### ISSUE THREAD

**Issue by iam-dev** [stove-labs/mip-token-standard#3]
It is recommended not to add the functions Mint, Burn, setTotalSupply, and setPaused to the token.ts file. Instead, these functions should be added as an extension, as shown in the OpenZeppelin ERC20Burnable.sol and ERC20Pausable.sol contracts, which can be found in the following links:

- https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/ERC20Burnable.sol
- https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/ERC20Pausable.sol
If you want to add a preset supply, you can do so using the OpenZeppelin ERC20PresetFixedSupply.sol contract, available at:

- https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/presets/ERC20PresetFixedSupply.sol
It is important to note that the token creator may have different requirements for their token, such as pre-minting or no burn function, which may require additional customization.

**Comment by maht0rz** [comment]
Inheritance with snarkyjs is currently rather difficult, please move your feedback to the main thread in #2, thanks!
